using System.Collections.Generic;
using UnityEngine;
using Mimas.Core.Content;

namespace Mimas.Client.Content
{
    /// <summary>
    /// The list of every JSON file under <c>Assets/_Game/Data</c>, as TextAsset references, with each
    /// file's path relative to that folder. Generated by the editor (see <c>GameDataManifestBuilder</c>)
    /// whenever the folder changes; never edited by hand. Referencing TextAssets, rather than copying
    /// their text, keeps this asset unchanged when a balance number changes and lets the Web build pack
    /// everything into the single <c>.data</c> download.
    /// </summary>
    [CreateAssetMenu(fileName = "GameDataManifest", menuName = "Mimas/Game Data Manifest")]
    public sealed class GameDataManifest : ScriptableObject
    {
        [SerializeField] private string[] _paths = new string[0];
        [SerializeField] private TextAsset[] _files = new TextAsset[0];

        public int Count => _paths != null ? _paths.Length : 0;

        public IReadOnlyList<string> Paths => _paths;

        /// <summary>The (path, text) pairs Core's catalogue loads. Missing assets are skipped with an error log.</summary>
        public List<ContentFile> ToContentFiles()
        {
            var result = new List<ContentFile>(Count);
            for (int i = 0; i < Count; i++)
            {
                TextAsset asset = i < _files.Length ? _files[i] : null;
                if (asset == null)
                {
                    Debug.LogError("[GameDataManifest] Entry '" + _paths[i] + "' has no TextAsset; rebuild the manifest (Mimas > Rebuild Game Data Manifest).", this);
                    continue;
                }
                result.Add(new ContentFile(_paths[i], asset.text));
            }
            return result;
        }

        /// <summary>Loads and links the catalogue. Throws <see cref="ContentLoadException"/> with every problem.</summary>
        public ContentCatalog LoadCatalog() => ContentCatalog.Load(ToContentFiles());

        /// <summary>True when the stored entries already equal <paramref name="paths"/> / <paramref name="files"/> pairwise.</summary>
        public bool Matches(IReadOnlyList<string> paths, IReadOnlyList<TextAsset> files)
        {
            if (paths == null || files == null || paths.Count != files.Count || paths.Count != Count) return false;
            for (int i = 0; i < paths.Count; i++)
            {
                if (!string.Equals(_paths[i], paths[i], System.StringComparison.Ordinal)) return false;
                if (_files[i] != files[i]) return false;
            }
            return true;
        }

#if UNITY_EDITOR
        /// <summary>Editor-only writer used by the manifest builder.</summary>
        public void SetEntries(string[] paths, TextAsset[] files)
        {
            if (paths == null || files == null || paths.Length != files.Length)
                throw new System.ArgumentException("paths and files must be parallel arrays.");
            _paths = (string[])paths.Clone();
            _files = (TextAsset[])files.Clone();
        }
#endif
    }
}
